// <auto-generated />
using BarBaridade;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarBaridade.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250430174000_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("BarBaridade.Bebida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<float>("TeorAlcoolico")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("TabelaBebidas");
                });
#pragma warning restore 612, 618
        }
    }
}
